/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    Changelog: typeof import('./../components/Changelog.vue')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/TailwindEmptyState.vue')['default']
    TailwindSpinner: typeof import('./../components/TailwindSpinner.vue')['default']
  }
}
